<?php
/**
 * Google reCAPTCHA v3 Verification Module for Altysier Group
 *
 * @package Altysier
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Verify Google reCAPTCHA v3 Token Server-Side
 *
 * @param string $token Token generated by frontend grecaptcha.execute
 * @param string $action Expected action name (e.g. 'contact_form')
 * @return array Array with 'success' (bool) and 'message' (string)
 */
function altysier_verify_recaptcha( $token, $action = 'contact_form' ) {
	$enabled = (bool) altysier_get_option( 'recaptcha_enabled', 0 );
	
	// If reCAPTCHA is not enabled or keys are empty, bypass check gracefully
	if ( ! $enabled ) {
		return array(
			'success' => true,
			'message' => 'reCAPTCHA disabled',
			'score'   => 1.0,
		);
	}

	$secret_key = altysier_get_option( 'recaptcha_secret_key', '' );
	if ( empty( $secret_key ) ) {
		return array(
			'success' => true,
			'message' => 'reCAPTCHA secret key not configured',
			'score'   => 1.0,
		);
	}

	if ( empty( $token ) ) {
		return array(
			'success' => false,
			'message' => __( 'Security verification failed: Token missing. Please refresh and try again.', 'altysier' ),
			'score'   => 0.0,
		);
	}

	$remote_ip = isset( $_SERVER['REMOTE_ADDR'] ) ? sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) ) : '';

	$response = wp_remote_post( 'https://www.google.com/recaptcha/api/siteverify', array(
		'timeout' => 10,
		'body'    => array(
			'secret'   => $secret_key,
			'response' => $token,
			'remoteip' => $remote_ip,
		),
	) );

	if ( is_wp_error( $response ) ) {
		// In case of remote API connection failure, log and allow legitimate users through
		error_log( '[Altysier reCAPTCHA] Verification request failed: ' . $response->get_error_message() );
		return array(
			'success' => true,
			'message' => 'Verification service unavailable, bypassing.',
			'score'   => 0.5,
		);
	}

	$body = wp_remote_retrieve_body( $response );
	$data = json_decode( $body, true );

	if ( ! is_array( $data ) || empty( $data['success'] ) ) {
		return array(
			'success' => false,
			'message' => __( 'Security verification failed. Please try submitting again.', 'altysier' ),
			'score'   => 0.0,
		);
	}

	$threshold = (float) altysier_get_option( 'recaptcha_threshold', 0.5 );
	$score     = isset( $data['score'] ) ? (float) $data['score'] : 0.0;

	if ( $score < $threshold ) {
		return array(
			'success' => false,
			'message' => __( 'Automated submission detected. Please contact our team directly via phone or email.', 'altysier' ),
			'score'   => $score,
		);
	}

	return array(
		'success' => true,
		'message' => 'Verified successfully.',
		'score'   => $score,
	);
}

/**
 * Output reCAPTCHA Script in Footer if Enabled
 */
function altysier_enqueue_recaptcha_script() {
	$enabled  = (bool) altysier_get_option( 'recaptcha_enabled', 0 );
	$site_key = altysier_get_option( 'recaptcha_site_key', '' );

	if ( $enabled && ! empty( $site_key ) ) {
		wp_enqueue_script(
			'google-recaptcha-v3',
			'https://www.google.com/recaptcha/api.js?render=' . esc_attr( $site_key ),
			array(),
			null,
			true
		);
	}
}
add_action( 'wp_enqueue_scripts', 'altysier_enqueue_recaptcha_script' );
